[metadata]
name = science-jubilee-interface
version = 0.1.0
description = Graphical interface for Science Jubilee experiments
license = MIT
url = https://github.com/Jubilee-CSL/science-jubilee-interface

[options]
packages = find:
package_dir =
    = src
python_requires = >=3.10

[options.packages.find]
where = src

[options.entry_points]
jubilee.paths =
    interface_dir = jubilee_interface:interface_dir

science_jubilee.deck =
    jubilee_interface = jubilee_interface:get_experiment_deck_dir
