#!/usr/bin/env python3
"""
labware_to_scad.py
──────────────────
Convert an Opentrons / custom-beta labware JSON definition into an OpenSCAD
file that renders a 3-D model of the plate.

Usage:
    python labware_to_scad.py labware.json              # writes labware.scad
    python labware_to_scad.py labware.json -o model.scad
    python labware_to_scad.py labware.json --fn 128     # smoother circles
"""

import argparse
import json
import sys
from pathlib import Path
from textwrap import indent


# ── Well shape renderers ─────────────────────────────────────────────────────

def scad_circular_well(well: dict) -> str:
    """Return an OpenSCAD translate+cylinder for a circular well."""
    x      = well["x"]
    y      = well["y"]
    z_bot  = well["z"]
    depth  = well["depth"]
    diam   = well["diameter"]
    return (
        f"translate([{x}, {y}, {z_bot}])\n"
        f"    cylinder(d={diam}, h={depth} + 1);"
    )


def scad_rectangular_well(well: dict) -> str:
    """Return an OpenSCAD translate+cube for a rectangular well."""
    x      = well["x"]
    y      = well["y"]
    z_bot  = well["z"]
    depth  = well["depth"]
    xdim   = well["xDimension"]
    ydim   = well["yDimension"]
    # JSON x/y is well centre; OpenSCAD cube origin is corner → shift by half dims
    ox = x - xdim / 2
    oy = y - ydim / 2
    return (
        f"translate([{ox}, {oy}, {z_bot}])\n"
        f"    cube([{xdim}, {ydim}, {depth} + 1]);"
    )


def scad_well_cutout(name: str, well: dict) -> str:
    """Dispatch to the right shape renderer and wrap in a comment."""
    shape = well.get("shape", "circular")
    if shape == "circular":
        body = scad_circular_well(well)
    elif shape == "rectangular":
        body = scad_rectangular_well(well)
    else:
        # Fallback: treat unknown shapes as circular if diameter present
        if "diameter" in well:
            body = scad_circular_well(well)
        else:
            print(f"  Warning: unknown shape '{shape}' for well {name}, skipping.", file=sys.stderr)
            return ""
    return f"// Well {name}\n{body}"


# ── Plate body renderer ──────────────────────────────────────────────────────

def scad_plate_body(dims: dict, corner_r: float) -> str:
    lx = dims["xDimension"]
    ly = dims["yDimension"]
    lz = dims["zDimension"]
    if corner_r > 0:
        return (
            f"// Outer plate body (rounded corners via hull)\n"
            f"hull() {{\n"
            f"    for (cx = [{corner_r}, {lx - corner_r}],\n"
            f"         cy = [{corner_r}, {ly - corner_r}])\n"
            f"        translate([cx, cy, 0])\n"
            f"            cylinder(r={corner_r}, h={lz});\n"
            f"}}"
        )
    else:
        return (
            f"// Outer plate body (sharp corners)\n"
            f"cube([{lx}, {ly}, {lz}]);"
        )


# ── Main code-generation function ────────────────────────────────────────────

def generate_scad(data: dict, fn: int = 64, corner_r: float = 3.0, simplified: bool = False) -> str:
    """
    Generate OpenSCAD for a labware.

    simplified=True (default in deck exporter) → just the outer bounding box,
    no well cutouts. Renders in <1 s per labware regardless of well count.
    simplified=False → full difference() with all well cylinders/cubes.
    """
    if simplified:
        dims = data["dimensions"]
        meta = data.get("metadata", {})
        params = data.get("parameters", {})
        lx = dims["xDimension"]
        ly = dims["yDimension"]
        lz = dims["zDimension"]
        name = meta.get("displayName", params.get("loadName", "labware"))
        return (
            f"// {name} (simplified — outer body only)\n"
            f"$fn = {fn};\n"
            f"cube([{lx}, {ly}, {lz}]);\n"
        )
    
    meta   = data.get("metadata", {})
    dims   = data["dimensions"]
    wells  = data["wells"]
    params = data.get("parameters", {})

    display_name = meta.get("displayName", params.get("loadName", "labware"))
    load_name    = params.get("loadName", "unknown")

    # Collect well shape info for the header comment
    shapes = {w.get("shape", "circular") for w in wells.values()}
    shape_str = ", ".join(sorted(shapes))

    # ── File header ──────────────────────────────────────────────────────────
    lines = [
        f"// ═══════════════════════════════════════════════════════════════════",
        f"// 3-D model: {display_name}",
        f"// Load name: {load_name}",
        f"// Generated by labware_to_scad.py",
        f"// Well shape(s): {shape_str}",
        f"// ═══════════════════════════════════════════════════════════════════",
        f"",
        f"// ── Render quality ─────────────────────────────────────────────────",
        f"$fn = {fn};   // circle/cylinder facets",
        f"",
        f"// ── Plate dimensions ────────────────────────────────────────────────",
        f"plate_x = {dims['xDimension']};",
        f"plate_y = {dims['yDimension']};",
        f"plate_z = {dims['zDimension']};",
        f"",
        f"// ── Corner rounding radius (set to 0 for sharp corners) ─────────────",
        f"corner_r = {corner_r};",
        f"",
    ]

    # ── Model ────────────────────────────────────────────────────────────────
    lines += [
        "// ── Model ───────────────────────────────────────────────────────────",
        "difference() {",
        "",
    ]

    # Plate body (indented inside difference)
    plate_body = scad_plate_body(dims, corner_r)
    lines.append(indent(plate_body, "    "))
    lines.append("")

    # Well cutouts
    lines.append("    // ── Well cutouts ───────────────────────────────────────")
    for name, well in wells.items():
        cutout = scad_well_cutout(name, well)
        if cutout:
            lines.append(indent(cutout, "    "))

    lines += ["}", ""]

    return "\n".join(lines)


# ── Placed-labware generator (used by deck_3d_exporter) ─────────────────────

def generate_scad_placed(
    data: dict,
    x_mm: float,
    y_mm: float,
    z_mm: float = 0.0,
    rotation_deg: float = 0.0,
    fn: int = 64,
    corner_r: float = 3.0,
    simplified: bool = True,
) -> str:
    """
    Place un labware Opentrons dans le repère Jubilee.

    simplified=True (défaut) : body = simple cube, rendu OpenSCAD < 1 s.
    simplified=False          : body complet avec découpe des puits.

    Convention : Opentrons X = Jubilee X, pas de rotation de base.
    (x_mm, y_mm) = coin min-AABB = valeur `coordinates` dans experience.json.
    """
    import math

    dims = data["dimensions"]
    xdim = float(dims["xDimension"])
    ydim = float(dims["yDimension"])

    total_angle = float(rotation_deg)
    rad = math.radians(total_angle)
    cos_a, sin_a = math.cos(rad), math.sin(rad)

    # Calcul de l'AABB après rotation pour ancrer le coin min sur (x_mm, y_mm)
    corners = [(0.0, 0.0), (xdim, 0.0), (xdim, ydim), (0.0, ydim)]
    rotated = [(cx * cos_a - cy * sin_a, cx * sin_a + cy * cos_a) for cx, cy in corners]
    min_rx = min(p[0] for p in rotated)
    min_ry = min(p[1] for p in rotated)

    tx = x_mm - min_rx
    ty = y_mm - min_ry

    body = generate_scad(data, fn=fn, corner_r=corner_r, simplified=simplified)

    header = (
        f"// ─── Placement Jubilee ──────────────────────────────────────\n"
        f"// coordinates (JSON) : ({x_mm:.2f}, {y_mm:.2f}, {z_mm:.2f}) mm\n"
        f"// Rotation : {rotation_deg}°   Labware dims : xDim={xdim}, yDim={ydim}\n"
        f"// Mode : {'simplifié (boîte)' if simplified else 'complet (avec puits)'}\n"
    )
    return (
        f"{header}\n"
        f"translate([{tx:.3f}, {ty:.3f}, {z_mm:.3f}])\n"
        f"rotate([0, 0, {total_angle}])\n"
        f"{{\n"
        f"{indent(body, '    ')}\n"
        f"}}\n"
    )


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Convert a labware JSON definition to an OpenSCAD model."
    )
    parser.add_argument("json_file", help="Path to the labware JSON file")
    parser.add_argument(
        "-o", "--output",
        help="Output .scad file path (default: same name as input with .scad extension)"
    )
    parser.add_argument(
        "--fn", type=int, default=64,
        help="OpenSCAD $fn value for circle resolution (default: 64)"
    )
    parser.add_argument(
        "--corner-radius", type=float, default=3.0,
        help="Plate corner rounding radius in mm (default: 3.0; set 0 for sharp)"
    )
    args = parser.parse_args()

    json_path = Path(args.json_file)
    if not json_path.exists():
        print(f"Error: file not found: {json_path}", file=sys.stderr)
        sys.exit(1)

    with open(json_path) as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error: invalid JSON – {e}", file=sys.stderr)
            sys.exit(1)

    # Validate required keys
    for key in ("dimensions", "wells"):
        if key not in data:
            print(f"Error: missing required key '{key}' in JSON.", file=sys.stderr)
            sys.exit(1)

    scad = generate_scad(data, fn=args.fn, corner_r=args.corner_radius)

    out_path = Path(args.output) if args.output else json_path.with_suffix(".scad")
    out_path.write_text(scad)
    print(f"Written: {out_path}")

    # Print a quick summary
    wells = data["wells"]
    dims  = data["dimensions"]
    print(f"  Plate : {dims['xDimension']} × {dims['yDimension']} × {dims['zDimension']} mm")
    print(f"  Wells : {len(wells)}")
    shapes = {w.get('shape','circular') for w in wells.values()}
    print(f"  Shape : {', '.join(sorted(shapes))}")


if __name__ == "__main__":
    main()
